export enum AgentTaskStatus {
  AWAITING_PLAN_APPROVAL = 'AWAITING_PLAN_APPROVAL',
  PLAN_APPROVED = 'PLAN_APPROVED',
  PLAN_REJECTED = 'PLAN_REJECTED',
  RUNNING = 'RUNNING',
  AWAITING_STEP_APPROVAL = 'AWAITING_STEP_APPROVAL',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
