export enum AgentCapability {
  ANSWER_QUESTION = 'ANSWER_QUESTION',
  FIND_FILES = 'FIND_FILES',
  EXPLAIN_CODE = 'EXPLAIN_CODE',
  PROPOSE_PATCH = 'PROPOSE_PATCH',
  GENERATE_TESTS = 'GENERATE_TESTS',
  CREATE_PR_DRAFT = 'CREATE_PR_DRAFT',
  SCAFFOLD_PROJECT = 'SCAFFOLD_PROJECT',
}
