export enum KnowledgeSourceType {
  PROCESS_DOC = 'PROCESS_DOC',
  ENGINEERING_STANDARD = 'ENGINEERING_STANDARD',
  TOOL_DOC = 'TOOL_DOC',
  WEBPAGE = 'WEBPAGE',
  MARKDOWN = 'MARKDOWN',
  PLAIN_TEXT = 'PLAIN_TEXT',
  REPO_FILE = 'REPO_FILE',
}
