import { PrDraftStatus } from '../../../common/enums/pr-draft-status.enum';
import { RiskLevel } from '../../../common/enums/risk-level.enum';

export class CreatePrDraftAgentResponseDto {
  /** ID of the AgentRun that tracked this operation. */
  runId: string;

  /** ID of the PullRequestDraft persistence record. */
  prDraftId: string;

  /** GitHub PR number, if the PR was successfully created on GitHub. */
  prNumber: number | null;

  /** GitHub PR URL, if the PR was successfully created on GitHub. */
  prUrl: string | null;

  /** PR title generated by the LLM. */
  title: string;

  /** Full PR body in GitHub-flavoured markdown. */
  body: string;

  /** The feature branch created for this PR. */
  headBranch: string;

  /** The branch the PR targets. */
  baseBranch: string;

  /** GitHub labels applied to the PR. */
  labels: string[];

  /** Pre-merge checklist items included in the PR body. */
  checklist: string[];

  /** Risk level inherited from the source patch. */
  riskLevel: RiskLevel;

  /** Whether the PR was opened as a draft. */
  isDraft: boolean;

  /** Persisted status of the PR draft record. */
  status: PrDraftStatus;

  /** Wall-clock duration of the entire orchestration in milliseconds. */
  durationMs: number;
}
